### ISSUE TITLE
Des fonctions définis plusieurs fois

### ISSUE THREAD

**Issue by atrantan** [NicolasRenson/arduino#3]
Les fonctions `loop()` et `setup()` ont été définis plusieurs fois. Avez vous compris l'intérêt de ces fonctions ?
https://github.com/NicolasRenson/arduino/blob/c5a283bdf66cb58d0aec71019f7a2bf11c138597/circuit_de_prevention.ino#L5-L17 
https://github.com/NicolasRenson/arduino/blob/c5a283bdf66cb58d0aec71019f7a2bf11c138597/code_deplacement_robot.ino#L17-L40

**Comment by fourcadeantoine** [comment]
oui j'ai compris l'intérêt de ses fonctions. Je souhaite dans un premier temps testé les programmes séparément avant d'en faire un même programme.

**Comment by atrantan** [comment]
@fourcadeantoine Ok. Mais le bot ne sera pas en mesure de tester ton code du coup. Il faudrait créer une branche Github pour chaque programme, et ainsi faire apparaître `loop()` et `setup()` une fois.
